set_color core_color, [38, 70, 83]
set_color surf_color, [42, 157, 143]
set_color site_color, [233, 196, 106]
color gray80, all
color surf_color, resi 10 and chain A
color surf_color, resi 11 and chain A
color core_color, resi 12 and chain A
color surf_color, resi 13 and chain A
color core_color, resi 14 and chain A
color core_color, resi 15 and chain A
color core_color, resi 16 and chain A
color core_color, resi 17 and chain A
color core_color, resi 18 and chain A
color core_color, resi 19 and chain A
color core_color, resi 20 and chain A
color core_color, resi 21 and chain A
color core_color, resi 22 and chain A
color core_color, resi 23 and chain A
color core_color, resi 24 and chain A
color core_color, resi 25 and chain A
color core_color, resi 26 and chain A
color core_color, resi 27 and chain A
color core_color, resi 28 and chain A
color core_color, resi 29 and chain A
color core_color, resi 30 and chain A
color core_color, resi 31 and chain A
color core_color, resi 32 and chain A
color core_color, resi 33 and chain A
color core_color, resi 34 and chain A
color core_color, resi 35 and chain A
color core_color, resi 36 and chain A
color surf_color, resi 56 and chain A
color core_color, resi 57 and chain A
color core_color, resi 58 and chain A
color core_color, resi 59 and chain A
color core_color, resi 60 and chain A
color core_color, resi 61 and chain A
color core_color, resi 62 and chain A
color core_color, resi 63 and chain A
color core_color, resi 64 and chain A
color core_color, resi 65 and chain A
color core_color, resi 66 and chain A
show spheres, resi 67 and chain A
color site_color, resi 67 and chain A
color core_color, resi 68 and chain A
show spheres, resi 69 and chain A
color site_color, resi 69 and chain A
color core_color, resi 70 and chain A
show spheres, resi 71 and chain A
color site_color, resi 71 and chain A
show spheres, resi 72 and chain A
color site_color, resi 72 and chain A
color core_color, resi 73 and chain A
color core_color, resi 74 and chain A
color core_color, resi 75 and chain A
color core_color, resi 76 and chain A
color core_color, resi 77 and chain A
color core_color, resi 78 and chain A
color core_color, resi 79 and chain A
color core_color, resi 80 and chain A
color surf_color, resi 81 and chain A
color surf_color, resi 82 and chain A
color core_color, resi 83 and chain A
color core_color, resi 84 and chain A
color core_color, resi 85 and chain A
color core_color, resi 86 and chain A
color core_color, resi 87 and chain A
color core_color, resi 88 and chain A
color core_color, resi 89 and chain A
show spheres, resi 90 and chain A
color site_color, resi 90 and chain A
color core_color, resi 91 and chain A
color core_color, resi 92 and chain A
color core_color, resi 93 and chain A
color core_color, resi 94 and chain A
color core_color, resi 95 and chain A
color core_color, resi 96 and chain A
color core_color, resi 97 and chain A
color core_color, resi 98 and chain A
color core_color, resi 99 and chain A
color core_color, resi 100 and chain A
color core_color, resi 101 and chain A
color core_color, resi 102 and chain A
color core_color, resi 103 and chain A
color core_color, resi 104 and chain A
color core_color, resi 105 and chain A
color core_color, resi 106 and chain A
color surf_color, resi 107 and chain A
color surf_color, resi 108 and chain A
color core_color, resi 109 and chain A
color surf_color, resi 110 and chain A
color surf_color, resi 111 and chain A
color surf_color, resi 112 and chain A
color surf_color, resi 113 and chain A
color surf_color, resi 114 and chain A
color surf_color, resi 115 and chain A
color core_color, resi 116 and chain A
color core_color, resi 117 and chain A
color core_color, resi 118 and chain A
color surf_color, resi 119 and chain A
color core_color, resi 120 and chain A
color core_color, resi 121 and chain A
color surf_color, resi 122 and chain A
color surf_color, resi 123 and chain A
color surf_color, resi 124 and chain A
color core_color, resi 125 and chain A
color surf_color, resi 126 and chain A
color surf_color, resi 127 and chain A
color core_color, resi 128 and chain A
color core_color, resi 129 and chain A
color surf_color, resi 130 and chain A
color core_color, resi 131 and chain A
color core_color, resi 132 and chain A
color core_color, resi 133 and chain A
color core_color, resi 134 and chain A
color core_color, resi 135 and chain A
color core_color, resi 136 and chain A
color core_color, resi 137 and chain A
color core_color, resi 138 and chain A
color core_color, resi 139 and chain A
color core_color, resi 140 and chain A
color core_color, resi 141 and chain A
color core_color, resi 142 and chain A
color core_color, resi 143 and chain A
show spheres, resi 144 and chain A
color site_color, resi 144 and chain A
color core_color, resi 145 and chain A
color core_color, resi 146 and chain A
color core_color, resi 147 and chain A
color core_color, resi 148 and chain A
color core_color, resi 149 and chain A
color core_color, resi 150 and chain A
color core_color, resi 151 and chain A
color core_color, resi 152 and chain A
color core_color, resi 153 and chain A
color core_color, resi 154 and chain A
color core_color, resi 155 and chain A
color core_color, resi 156 and chain A
color core_color, resi 157 and chain A
color surf_color, resi 158 and chain A
color core_color, resi 159 and chain A
color core_color, resi 160 and chain A
color surf_color, resi 161 and chain A
color core_color, resi 162 and chain A
color surf_color, resi 163 and chain A
color core_color, resi 164 and chain A
color core_color, resi 165 and chain A
color core_color, resi 166 and chain A
color core_color, resi 167 and chain A
color core_color, resi 168 and chain A
color core_color, resi 169 and chain A
color core_color, resi 170 and chain A
color core_color, resi 171 and chain A
color core_color, resi 172 and chain A
color core_color, resi 173 and chain A
color core_color, resi 174 and chain A
color core_color, resi 175 and chain A
color core_color, resi 176 and chain A
color core_color, resi 177 and chain A
color core_color, resi 178 and chain A
color core_color, resi 179 and chain A
color core_color, resi 180 and chain A
color core_color, resi 181 and chain A
color core_color, resi 182 and chain A
color core_color, resi 183 and chain A
color core_color, resi 190 and chain A
color core_color, resi 191 and chain A
color core_color, resi 192 and chain A
color core_color, resi 193 and chain A
color core_color, resi 194 and chain A
color core_color, resi 195 and chain A
color core_color, resi 196 and chain A
color core_color, resi 197 and chain A
color core_color, resi 198 and chain A
color core_color, resi 199 and chain A
color core_color, resi 200 and chain A
color core_color, resi 201 and chain A
color core_color, resi 202 and chain A
color core_color, resi 203 and chain A
color core_color, resi 204 and chain A
color core_color, resi 205 and chain A
color core_color, resi 206 and chain A
color core_color, resi 207 and chain A
color core_color, resi 208 and chain A
color core_color, resi 209 and chain A
color core_color, resi 210 and chain A
color surf_color, resi 211 and chain A
color surf_color, resi 212 and chain A
color surf_color, resi 213 and chain A
color surf_color, resi 214 and chain A
color surf_color, resi 215 and chain A
color surf_color, resi 216 and chain A
color surf_color, resi 217 and chain A
color surf_color, resi 218 and chain A
color core_color, resi 219 and chain A
color surf_color, resi 220 and chain A
color surf_color, resi 221 and chain A
color surf_color, resi 222 and chain A
color core_color, resi 223 and chain A
color surf_color, resi 224 and chain A
color surf_color, resi 225 and chain A
color surf_color, resi 226 and chain A
color surf_color, resi 227 and chain A
color surf_color, resi 228 and chain A
color surf_color, resi 229 and chain A
color surf_color, resi 230 and chain A
color core_color, resi 231 and chain A
color core_color, resi 232 and chain A
color surf_color, resi 233 and chain A
color core_color, resi 234 and chain A
color surf_color, resi 235 and chain A
color core_color, resi 236 and chain A
color surf_color, resi 237 and chain A
color core_color, resi 238 and chain A
color surf_color, resi 239 and chain A
color surf_color, resi 240 and chain A
color core_color, resi 241 and chain A
color core_color, resi 242 and chain A
color core_color, resi 243 and chain A
color core_color, resi 244 and chain A
color core_color, resi 245 and chain A
color core_color, resi 246 and chain A
color core_color, resi 247 and chain A
color core_color, resi 248 and chain A
color core_color, resi 249 and chain A
color core_color, resi 250 and chain A
color core_color, resi 251 and chain A
color core_color, resi 252 and chain A
color core_color, resi 253 and chain A
color core_color, resi 254 and chain A
color core_color, resi 255 and chain A
color core_color, resi 256 and chain A
color core_color, resi 257 and chain A
color core_color, resi 258 and chain A
color core_color, resi 259 and chain A
color core_color, resi 260 and chain A
color core_color, resi 261 and chain A
color core_color, resi 262 and chain A
color core_color, resi 263 and chain A
color core_color, resi 264 and chain A
color core_color, resi 265 and chain A
color core_color, resi 266 and chain A
color surf_color, resi 267 and chain A
color core_color, resi 268 and chain A
color core_color, resi 269 and chain A
color surf_color, resi 270 and chain A
color surf_color, resi 271 and chain A
color surf_color, resi 272 and chain A
color surf_color, resi 273 and chain A
color surf_color, resi 274 and chain A
color surf_color, resi 275 and chain A
color surf_color, resi 276 and chain A
color surf_color, resi 277 and chain A
color core_color, resi 278 and chain A
color surf_color, resi 279 and chain A
color core_color, resi 280 and chain A
color core_color, resi 281 and chain A
color core_color, resi 282 and chain A
color core_color, resi 283 and chain A
color core_color, resi 284 and chain A
color core_color, resi 285 and chain A
color core_color, resi 286 and chain A
color core_color, resi 287 and chain A
color core_color, resi 288 and chain A
color core_color, resi 289 and chain A
color core_color, resi 290 and chain A
color core_color, resi 291 and chain A
color core_color, resi 292 and chain A
show spheres, resi 293 and chain A
color site_color, resi 293 and chain A
color core_color, resi 294 and chain A
color core_color, resi 295 and chain A
color core_color, resi 296 and chain A
color core_color, resi 297 and chain A
color core_color, resi 298 and chain A
color core_color, resi 299 and chain A
color core_color, resi 300 and chain A
color core_color, resi 301 and chain A
color core_color, resi 302 and chain A
color core_color, resi 303 and chain A
color surf_color, resi 304 and chain A
color surf_color, resi 305 and chain A
color surf_color, resi 306 and chain A
color surf_color, resi 307 and chain A
color surf_color, resi 308 and chain A
color surf_color, resi 309 and chain A
color surf_color, resi 310 and chain A
color surf_color, resi 311 and chain A
color surf_color, resi 312 and chain A
color surf_color, resi 313 and chain A
color surf_color, resi 314 and chain A
color surf_color, resi 315 and chain A
color surf_color, resi 316 and chain A
color surf_color, resi 317 and chain A
color surf_color, resi 318 and chain A
color surf_color, resi 319 and chain A
color surf_color, resi 320 and chain A
color surf_color, resi 321 and chain A
color core_color, resi 322 and chain A
color core_color, resi 323 and chain A
color surf_color, resi 324 and chain A
color core_color, resi 325 and chain A
color core_color, resi 326 and chain A
color surf_color, resi 327 and chain A
color core_color, resi 328 and chain A
color core_color, resi 329 and chain A
color surf_color, resi 330 and chain A
color surf_color, resi 331 and chain A
color surf_color, resi 332 and chain A
color core_color, resi 333 and chain A
color surf_color, resi 334 and chain A
color surf_color, resi 335 and chain A
color core_color, resi 336 and chain A
color core_color, resi 337 and chain A
color core_color, resi 338 and chain A
color core_color, resi 339 and chain A
color core_color, resi 340 and chain A
color core_color, resi 341 and chain A
color core_color, resi 342 and chain A
color core_color, resi 343 and chain A
color core_color, resi 344 and chain A
color core_color, resi 345 and chain A
color core_color, resi 346 and chain A
color core_color, resi 347 and chain A
color core_color, resi 348 and chain A
color core_color, resi 349 and chain A
color core_color, resi 350 and chain A
color core_color, resi 351 and chain A
color core_color, resi 352 and chain A
color core_color, resi 353 and chain A
color core_color, resi 354 and chain A
color core_color, resi 355 and chain A
color core_color, resi 356 and chain A
color core_color, resi 357 and chain A
color core_color, resi 358 and chain A
color core_color, resi 359 and chain A
color core_color, resi 360 and chain A
color core_color, resi 361 and chain A
color core_color, resi 362 and chain A
color core_color, resi 363 and chain A
color core_color, resi 364 and chain A
color core_color, resi 365 and chain A
color core_color, resi 366 and chain A
color surf_color, resi 367 and chain A
color surf_color, resi 368 and chain A
color surf_color, resi 369 and chain A
color surf_color, resi 370 and chain A
color core_color, resi 371 and chain A
color surf_color, resi 372 and chain A
color surf_color, resi 373 and chain A
color surf_color, resi 374 and chain A
color surf_color, resi 375 and chain A
color surf_color, resi 376 and chain A
color surf_color, resi 377 and chain A
color surf_color, resi 378 and chain A
color surf_color, resi 379 and chain A
color surf_color, resi 380 and chain A
color surf_color, resi 381 and chain A
color surf_color, resi 382 and chain A
color surf_color, resi 383 and chain A
color surf_color, resi 384 and chain A
color surf_color, resi 385 and chain A
color surf_color, resi 386 and chain A
color core_color, resi 387 and chain A
color core_color, resi 388 and chain A
color core_color, resi 389 and chain A
color core_color, resi 390 and chain A
color core_color, resi 391 and chain A
color core_color, resi 392 and chain A
color core_color, resi 393 and chain A
color core_color, resi 394 and chain A
color core_color, resi 395 and chain A
color core_color, resi 396 and chain A
color core_color, resi 397 and chain A
color core_color, resi 398 and chain A
color core_color, resi 399 and chain A
color core_color, resi 400 and chain A
color core_color, resi 401 and chain A
color core_color, resi 402 and chain A
color core_color, resi 403 and chain A
color core_color, resi 404 and chain A
color core_color, resi 405 and chain A
color core_color, resi 406 and chain A
color core_color, resi 407 and chain A
color core_color, resi 408 and chain A
color core_color, resi 409 and chain A
color core_color, resi 410 and chain A
color core_color, resi 411 and chain A
color core_color, resi 412 and chain A
show spheres, resi 413 and chain A
color site_color, resi 413 and chain A
color core_color, resi 414 and chain A
color core_color, resi 415 and chain A
show spheres, resi 416 and chain A
color site_color, resi 416 and chain A
show spheres, resi 417 and chain A
color site_color, resi 417 and chain A
color core_color, resi 418 and chain A
color core_color, resi 419 and chain A
color core_color, resi 420 and chain A
color core_color, resi 421 and chain A
color core_color, resi 422 and chain A
color core_color, resi 423 and chain A
color core_color, resi 424 and chain A
color core_color, resi 425 and chain A
color core_color, resi 426 and chain A
color core_color, resi 427 and chain A
color core_color, resi 428 and chain A
color core_color, resi 429 and chain A
color core_color, resi 430 and chain A
color core_color, resi 431 and chain A
color core_color, resi 432 and chain A
color core_color, resi 433 and chain A
color core_color, resi 434 and chain A
color core_color, resi 435 and chain A
color core_color, resi 436 and chain A
color core_color, resi 437 and chain A
color core_color, resi 438 and chain A
color core_color, resi 439 and chain A
color core_color, resi 440 and chain A
color core_color, resi 441 and chain A
color core_color, resi 442 and chain A
color core_color, resi 443 and chain A
color core_color, resi 444 and chain A
color core_color, resi 445 and chain A
color core_color, resi 446 and chain A
color core_color, resi 447 and chain A
color core_color, resi 448 and chain A
color core_color, resi 449 and chain A
color core_color, resi 450 and chain A
color core_color, resi 451 and chain A
color core_color, resi 452 and chain A
color core_color, resi 453 and chain A
color core_color, resi 454 and chain A
color core_color, resi 455 and chain A
color core_color, resi 456 and chain A
color core_color, resi 457 and chain A
color core_color, resi 458 and chain A
color core_color, resi 459 and chain A
color core_color, resi 460 and chain A
color core_color, resi 461 and chain A
color core_color, resi 462 and chain A
color core_color, resi 463 and chain A
color core_color, resi 464 and chain A
color surf_color, resi 465 and chain A
color surf_color, resi 466 and chain A
color surf_color, resi 467 and chain A
color surf_color, resi 468 and chain A
color surf_color, resi 469 and chain A
color surf_color, resi 470 and chain A
color surf_color, resi 471 and chain A
color surf_color, resi 472 and chain A
color surf_color, resi 473 and chain A
color surf_color, resi 474 and chain A
color surf_color, resi 475 and chain A
color surf_color, resi 476 and chain A
color surf_color, resi 477 and chain A
color surf_color, resi 478 and chain A
color surf_color, resi 479 and chain A
color surf_color, resi 480 and chain A
color surf_color, resi 481 and chain A
color surf_color, resi 482 and chain A
color surf_color, resi 483 and chain A
color surf_color, resi 510 and chain A
color surf_color, resi 511 and chain A
color surf_color, resi 512 and chain A
color surf_color, resi 513 and chain A
color core_color, resi 514 and chain A
color surf_color, resi 515 and chain A
color surf_color, resi 516 and chain A
color surf_color, resi 517 and chain A
color core_color, resi 518 and chain A
color core_color, resi 519 and chain A
color surf_color, resi 520 and chain A
color core_color, resi 521 and chain A
color core_color, resi 522 and chain A
color core_color, resi 523 and chain A
color core_color, resi 524 and chain A
color core_color, resi 525 and chain A
color core_color, resi 526 and chain A
color core_color, resi 527 and chain A
color core_color, resi 528 and chain A
color core_color, resi 529 and chain A
color core_color, resi 530 and chain A
color core_color, resi 531 and chain A
color core_color, resi 532 and chain A
color core_color, resi 533 and chain A
color core_color, resi 534 and chain A
color core_color, resi 535 and chain A
color core_color, resi 536 and chain A
color core_color, resi 537 and chain A
color core_color, resi 538 and chain A
color core_color, resi 539 and chain A
color core_color, resi 540 and chain A
color core_color, resi 541 and chain A
color core_color, resi 542 and chain A
color core_color, resi 543 and chain A
color core_color, resi 544 and chain A
color core_color, resi 545 and chain A
color core_color, resi 546 and chain A
color core_color, resi 547 and chain A
color surf_color, resi 548 and chain A
color surf_color, resi 549 and chain A
color surf_color, resi 550 and chain A
color surf_color, resi 551 and chain A
color surf_color, resi 552 and chain A
color surf_color, resi 553 and chain A
color surf_color, resi 554 and chain A
color surf_color, resi 555 and chain A
color surf_color, resi 556 and chain A
color surf_color, resi 557 and chain A
color surf_color, resi 558 and chain A
color surf_color, resi 559 and chain A
color surf_color, resi 560 and chain A
color surf_color, resi 561 and chain A
show cartoon
set transparency, 0.5, resi 1-1000
util.cnc
